{% set name = "chartpress" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aaa905f91b14058107471bc4059b1f6e0390b2cdbfdec418ee3d64a3e2e392dc

build:
  number: 0
  entry_points:
    - chartpress = chartpress:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

# This section should be kept updated with chartpress' setup.py file:
# https://github.com/jupyterhub/chartpress/blob/main/setup.py#L47-L52
#
requirements:
  host:
    - pip
    - python >=3.7
  run:
    - docker-py >=3.2.0, !=5.0.0
    - python >=3.7
    - ruamel.yaml >=0.15.44

test:
  commands:
    - chartpress --help

about:
  home: https://github.com/jupyterhub/chartpress
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'ChartPress: render and publish helm charts and images'
  doc_url: https://github.com/jupyterhub/chartpress
  dev_url: https://github.com/jupyterhub/chartpress

extra:
  recipe-maintainers:
    - consideratio
    - manics
