{% set name = "chartpress" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32feaf572bdaa9ccf2855ba9eedb37710473134236764026a15f56be0f4f1c29

build:
  number: 0
  entry_points:
    - chartpress = chartpress:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

# This section should be kept updated with chartpress' setup.py file:
# https://github.com/jupyterhub/chartpress/blob/main/setup.py#L47-L52
#
requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - docker-py >=3.2.0, !=5.0.0
    - python >={{ python_min }}
    - ruamel.yaml >=0.15.44

test:
  requires:
    - python {{ python_min }}
  commands:
    - chartpress --help

about:
  home: https://github.com/jupyterhub/chartpress
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'ChartPress: render and publish helm charts and images'
  doc_url: https://github.com/jupyterhub/chartpress
  dev_url: https://github.com/jupyterhub/chartpress

extra:
  recipe-maintainers:
    - consideratio
    - manics
